
<?php
$_productCollection=$this->getItems();
$_helper = $this->helper('catalog/output');

$imgCdn = '//s3.cudsly.com/images/';
$pageTitle = Mage::getSingleton('cms/page')->getIdentifier();
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php
        $toolbar = Mage::app()->getLayout()->createBlock('catalog/product_list')->getToolbarBlock();
        $toolbar->setCollection( $_productCollection );
        echo $toolbar->toHtml();
        ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
             
                <?php $sku = explode('-', $_product->getSku()); ?>
                <?php $_sku = $sku[0];?>

                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="onsale-category-container-grid">
                        <?php echo Mage::helper('onsale')->getCategoryLabelHtml($_product); ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $imgCdn . $_sku . '/' . $_sku; ?>-1.jpg"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                    </div>

                    <div class="product-info">
                        <h2 class="product-brand"><?php $brand = $_product->getAttributeText('brand') ; ?><?php echo $brand; ?></h2>
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <div class="actions">
                            <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button>
                            <?php elseif($_product->isSaleable()): ?>
                                <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>

                        </div>
                    </div>
                </li>

            <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>


        <div class="toolbar-bottom">
            <?php

            $toolbar = Mage::app()->getLayout()->createBlock('catalog/product_list')->getToolbarBlock();
            $toolbar->setCollection( $_productCollection );
            echo $toolbar->toHtml();

            ?>
        </div>
    </div>
<?php endif; ?>

