<?php
/**
 * Abandoned Carts Alerts Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Cartalert
 * @version      3.6.2
 * @license:     HURXKDG7XXFyzvUh6YIaOzBxXgSru0OEdm0JvUmsP0
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
/* @var $this Aitoc_Aitsys_Block_Notification */
?>
<div class="fieldset">
  <div class="news">
      <?php foreach ($this->getNews() as $item) { ?>
          <dl class="item">
            <dt>
                <?php if (isset($item['title']) && $item['title']) { ?>
                    <h2><?php echo $item['title']?></h2>
                <?php } ?>
            </dt>
            <dd>
              <?php echo $item['content']?>
            </dd>
          </dl>
      <?php } ?>
  </div>
</div>