<div id="co-billing-form">
    <h3><?php echo $this->__('Name & Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="wide">
            <label for="billing-address-select" class="notice"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
                <li class="wide"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <div class="clear"></div>
                <li class="wide">
        <?php if(!$this->isCustomerLoggedIn()): ?>

                        <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>

        <?php endif; ?>
                </li>
                <div class="clear"></div>
        <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide" style="display: none;">
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
        <?php endfor; ?>
                <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                <li class="wide">
                    <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
                <?php endif; ?>
                <li class="address-additional-separator"></li>

                <li class="wide">

                        <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('Region / Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State / Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State / Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>

                </li>
                
                <li class="wide">

                        <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City / District') ?></label>
                        <div class="input-box">
                            <select class='validate-select required-entry' name="billing[city]" id='billing:city'><option value=''>Please select city...</option></select>   
                            <!--
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="billing:city" />-->
                        </div>
                    
                </li>

                <li class="wide">
    
                        <label for="billing:barangay" class="required"><em>*</em><?php echo $this->__('Barangay') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Barangay') ?>" name="billing[barangay]" value="<?php //echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:barangay" />
                        </div>
                    
                </li>
                
                <li class="wide">
                        <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>" />
                        </div>
		</li>
                <li class="wide">
                        <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                </li>
                <li class="wide">
                        <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Contact Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="validate-number input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                        </div>
                    
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                           
                            <?php if ($_dob->isEnabled()): ?>
 				<li class="wide">
                                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
				</li>
                            <?php endif; ?>
                            <?php if ($_gender->isEnabled()): ?>
				    <li class="wide">
                                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                     </li>
                            <?php endif ?>

                            <div class="clear"></div>
                        <?php endif ?>

                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                            <li>
                                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                    <?php endif ?>

                    
                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                	<div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
    </li>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>

    <!-- fix browser autocomplete -->
	<div style="display:none !important">
		<input type="text" autocomplete="off" value="" />
		<input type="password" autocomplete="off" value=""/>
	</div>
	<!-- end fix browser autocomplete -->
    
    <?php if(!$this->isCustomerLoggedIn()): ?>
    
    	<?php
    	$guest_allowed = $this->getQuote()->isAllowedGuestCheckout();
    	if($guest_allowed): ?>
	    <li class="control">
	            <input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?php echo  $this->__('Create an account for later use') ?>"  class="checkbox" /><label for="billing:create_account"><?php echo  $this->__('Create an account for later use') ?></label>
	    </li>
	    <?php else:?>
	    	<input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
	    <?php endif;?>
        
		<li class="fields <?php if($guest_allowed):?>hidden<?php endif;?>" id="register-customer-password">
			<div class="field">
				<label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[customer_password]" title="<?php echo $this->__('Password') ?>" id="billing:customer_password" class="input-text validate-password <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
			<div class="field">
				<label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
		</li>
		<div class="clear"></div>
    
    <?php endif;?>
    
    <?php if ($this->canShip()): ?>
        <li class="control <?php if (!Mage::helper('opc')->isShowShippingForm()):?>hidden<?php endif;?>">
            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>

</div>


<script type="text/javascript">
    //<![CDATA[

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    CITIES_ACTION = "<?php echo $this->getUrl('citydropdown/index/cities'); ?>";
    //]]>
</script>

<script type="text/javascript">
    //<![CDATA[
    var normalImput = '<input type="text" class=" input-text required-entry absolute-advice bil1" title="City" value="" id="billing:city" name="billing[city]" autocomplete="off">';
    var normalImputShip = "<select class='validate-select required-entry' id='shipping:city'><option value=''>Please select city...</option></select>";

    <?php if($this->getAddress()->getRegionId()): ?>
        document.observe("dom:loaded", function() {
            var action = CITIES_ACTION;
            var selectCountry = $('billing:country_id').value;
            var stateId = $('billing:region_id').value;
            var selectedCity = '<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>';
            getAjaxReqest(action, selectCountry, stateId, normalImput,selectedCity)
        });
    <?php endif?> 

    Event.observe($('billing:region_id'), 'change', function (event) {
        var selectedCity = false;
        var action = CITIES_ACTION;
        var selectCountry = $('billing:country_id').value;
        var stateId = $('billing:region_id').value;
        getAjaxReqest(action, selectCountry, stateId, normalImput,selectedCity)

    });

    Event.observe($('billing:country_id'), 'change', function (event) {
        var shipCity = $('shipping:city');
        $('billing:city').replace(normalImput);
        if (shipCity != null) {
            $('shipping:city').replace(normalImputShip);
        }

    });

     jQuery('.opc-col-left').on( 'change', '#billing\\:city', function(){
        var selectedCity = jQuery( this ).val();
        var action = CITIES_ACTION;
        var selectCountry = $('billing:country_id').value;
        var stateId = $('billing:region_id').value;
         //console.log("change");
        nxttarget = jQuery('.opc-col-left').find('#billing\\:barangay');
        jQuery.post( "<?php echo $this->getUrl('citydropdown/index/barangay'); ?>", { cityname: selectedCity})
            .done(function( data ) {
                nxttarget.replaceWith("<select class='validate-select required-entry' id='billing:barangay'><option value=''>Please select barangay...</option>" + data + "</select>");
        });  
         
        if (document.getElementById('billing:use_for_shipping_yes').checked) {
            //console.log("checked");
            getAjaxReqestShip(action, selectCountry, stateId, normalImputShip,selectedCity)
            target = jQuery('.opc-col-left').find('#shipping\\:city');
            target.filter(function() {
                return target.text() == selectedCity; 
            }).attr('selected', true);

            nxttarget2 = jQuery('.opc-col-left').find('#shipping\\:barangay');
            jQuery.post( "<?php echo $this->getUrl('citydropdown/index/barangay'); ?>", { cityname: selectedCity})
                .done(function( data ) {
                    nxttarget2.replaceWith("<select class='validate-select required-entry' id='shipping:barangay'><option value=''>Please select barangay...</option>" + data + "</select>");
                    jQuery('#shipping\\:barangay [value="' + nxttarget.val() + '"]').attr('selected', true);
            });            
          
            
        } else {
            //$('shipping:city').replace(normalImputShip);
        }
    });

    jQuery('.opc-col-left').on( 'change', '#billing\\:barangay', function(){
        //alert(jQuery( this ).val());
        jQuery("#billing\\:street2").val(jQuery( this ).val());
    });    

    jQuery( document ).ready( function() {

        jQuery('#billing-address-select').change( function(){
            var bill = jQuery('#billing\\:city').val();
                if(bill != ""){
                        var selectedCity = bill;
                        nxttarget = jQuery('.opc-col-left').find('#billing\\:barangay');
                        jQuery.post( "<?php echo $this->getUrl('citydropdown/index/barangay'); ?>", { cityname: selectedCity})
                            .done(function( data ) {
                                nxttarget.replaceWith("<select class='validate-select required-entry' id='billing:barangay'><option value=''>Please select barangay...</option>" + data + "</select>");
                                barangay = jQuery('#billing\\:street2').val();
                                jQuery('#billing\\:barangay [value="' + barangay + '"]').attr('selected', true);
                        });  
                }else{
                    nxttarget.replaceWith("<select class='validate-select required-entry' id='billing:barangay'><option value=''>Please select barangay...</option></select>"); 
                }           
        })
        
        jQuery('#shipping-address-select').change( function(){
            var bill = jQuery('#shipping\\:city').val();
                if(bill != ""){
                        var selectedCity = bill;
                        nxttarget = jQuery('.opc-col-left').find('#shipping\\:barangay');
                        jQuery.post( "<?php echo $this->getUrl('citydropdown/index/barangay'); ?>", { cityname: selectedCity})
                            .done(function( data ) {
                                nxttarget.replaceWith("<select class='validate-select required-entry' id='shipping:barangay'><option value=''>Please select barangay...</option>" + data + "</select>");
                                barangay = jQuery('#shipping\\:street2').val();
                                jQuery('#shipping\\:barangay [value="' + barangay + '"]').attr('selected', true);
                        });  
                }else{
                    nxttarget.replaceWith("<select class='validate-select required-entry' id='shipping:barangay'><option value=''>Please select barangay...</option></select>");                    
                }           
        })        
        
         jQuery('.opc-col-left').find('#billing\\:barangay').replaceWith("<select class='validate-select required-entry' id='billing:barangay'><option value=''>Please select barangay...</option></select>");
        jQuery('.opc-col-left').find('#shipping\\:barangay').replaceWith("<select class='validate-select required-entry' id='shipping:barangay'><option value=''>Please select barangay...</option></select>");
        
        <?php
        $address = Mage::getModel('checkout/session')->getQuote()->getBillingAddress()->getData();
        $shipppingaddress = Mage::getModel('checkout/session')->getQuote()->getShippingAddress()->getData();
        
        if($address["street"] != ""){
        ?>
             bill = '<?php echo $address["city"] ?>';
                if(bill != ""){
                        var selectedCity = bill;
                        nxttarget = jQuery('.opc-col-left').find('#billing\\:barangay');
                        jQuery.post( "<?php echo $this->getUrl('citydropdown/index/barangay'); ?>", { cityname: selectedCity})
                            .done(function( data ) {
                                nxttarget.replaceWith("<select class='validate-select required-entry' id='billing:barangay'><option value=''>Please select barangay...</option>" + data + "</select>");
                                barangay = jQuery('#billing\\:street2').val();
                                jQuery('#billing\\:barangay [value="' + barangay + '"]').attr('selected', true);
                        });  
                } 
       
        <?php
        }
        ?>
        
    })
    
    //]]>
</script>
<?php
//echo $address["street"].$address["city"].">>";
?>