<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile3
 * @version    3.0.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgCdn = '/scripts/mini.php?src=http://s3.cudsly.com/images/';
?>
<div class="products" id="product_list">
    <?php if(!$_productCollection->count()): ?>
        <div class="products__no-products">
            <?php echo $this->__('There are no products matching the selection.') ?>
        </div>
    <?php else: ?>
        <?php foreach ($_productCollection as $_product): ?>
            <?php $priceHtml = $this->getPriceHtml($_product, true); ?>
            <a class="product-card product-card--horizontal product-card--in-list" href="<?php echo $_product->getProductUrl() ?>">
                <p class="product-card__image-wrapper">
		    <?php $sku = explode('-', $_product->getSku()); ?>
		    <?php $_sku = $sku[0];?>
                    <img class="product-card__image" src="<?php echo $imgCdn . $_sku . '/' . $_sku; ?>-1.jpg&w=90" srcset="<?php echo $imgCdn . $_sku . '/' . $_sku; ?>-1.jpg&w=180 2x" width="90" height="90">
                </p>
                <div class="product-card__info">
                    <h3 class="product-card__title">
                        <?php echo $this->stripTags($_product->getName(), null, true) ?>
                    </h3>

                    <?php if (AW_Mobile3_Helper_Config::isCanDisplayStockStatusAtCatalog()):?>
                        <?php if($_product->isSaleable()): ?>
                            <p class="product-card__availability"><?php echo $this->__('In stock') ?></p>
                        <?php else: ?>
                            <p class="product-card__availability"><?php echo $this->__('Out of stock') ?></p>
                        <?php endif; ?>
                    <?php endif;?>

                    <div class="product-card__prices">
                        <?php echo $priceHtml;?>
                    </div>
                </div><!-- .product-card__info -->
            </a><!-- .product-card -->
        <?php endforeach; ?>
    <?php endif ?>
</div>
<?php echo $this->getToolbarHtml() ?>
<script>
    if (typeof pager != 'undefined') {
        pager.containerId = 'product_list';
    }
</script>
