<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
                <div class="squaredOne">
                    <?php $id = strtolower(str_replace(" ","",$_item->getLabel())) ?>
                    <input id="<?php echo $id?>"type="checkbox"<?php if ($_item->isSelected()): ?> checked="checked" <?php endif; ?>
                        <?php if ($this->helper('catalin_seo')->isAjaxEnabled()): ?>
                            onclick="window.location='<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>'"
                        <?php else: ?>
                            onclick="setLocation('<?php echo ($_item->isSelected()) ? $this->urlEscape($_item->getRemoveUrl()) : $this->urlEscape($_item->getUrl()) ?>')"
                        <?php endif; ?>
                        />
                    <label for="<?php echo $id?>"></label>
                        <span class="filter-label">
                               <?php echo $_item->getLabel() ?>
                        </span>

                </div>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>